---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ceres
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/skulesh01/Ceres
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ceres-releases
  namespace: flux-system
spec:
  interval: 5m
  path: ./config/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: ceres
