# Cert-Manager для автоматических TLS сертификатов
# CERES v3.1 - Задача 2.1
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
# Установка через Helm (выполняется через deployer.go)
# helm repo add jetstack https://charts.jetstack.io
# helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.13.0 --set installCRDs=true
---
# ClusterIssuer для самоподписанных сертификатов
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# ClusterIssuer для Let's Encrypt (для продакшена)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@ceres.local
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
