# Cert-Manager для автоматических TLS сертификатов
# CERES v3.1 - Задача 2.1
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
# Установка через Helm (выполняется через deployer.go)
# helm repo add jetstack https://charts.jetstack.io
# helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.13.0 --set installCRDs=true
---
# ClusterIssuer для самоподписанных сертификатов
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# Внутренняя CA ("по-взрослому" для локальной сети):
# 1) выпускаем один корневой CA сертификат (ceres-root-ca)
# 2) им подписываем все сертификаты для *.ceres.local (через ClusterIssuer ceres-ca)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ceres-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: CERES Root CA
  secretName: ceres-root-ca
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ceres-ca
spec:
  ca:
    secretName: ceres-root-ca
---
# ClusterIssuer для Let's Encrypt (для продакшена)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@ceres.local
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
