apiVersion: v1
kind: Namespace
metadata:
  name: ceres
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: ceres
type: Opaque
stringData:
  admin-password: K3yClo@k!2025
  db-password: ceres_postgres_2025
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: ceres
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgresql.ceres-core:5432/keycloak
  KC_DB_USERNAME: postgres
  KC_HOSTNAME: keycloak.ceres.local
  KC_HTTP_ENABLED: "true"
  KC_PROXY: edge
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: ceres
spec:
  selector:
    app: keycloak
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: ceres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:23.0.0
        args:
        - start
        - --optimized
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: admin-password
        - name: KC_DB
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_DB
        - name: KC_DB_URL
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_DB_URL
        - name: KC_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_DB_USERNAME
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: db-password
        - name: KC_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HOSTNAME
        - name: KC_HTTP_ENABLED
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HTTP_ENABLED
        - name: KC_PROXY
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_PROXY
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
