apiVersion: v1
kind: Namespace
metadata:
  name: ceres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: ceres
data: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: ceres
data:
  ceres-realm.json: |
    {
      "realm": "ceres",
      "enabled": true,
      "displayName": "CERES Platform",
      "registrationAllowed": false,
      "resetPasswordAllowed": true,
      "rememberMe": true,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "sslRequired": "none",
      "smtpServer": {
        "host": "mailcow-smtp.mailcow.svc.cluster.local",
        "port": "25",
        "from": "no-reply@ceres.local",
        "fromDisplayName": "CERES"
      },
      "clients": [
        {
          "clientId": "gitlab",
          "name": "GitLab",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "redirectUris": [
            "https://gitlab.ceres.local/users/auth/openid_connect/callback"
          ],
          "webOrigins": [
            "https://gitlab.ceres.local"
          ],
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": false,
          "attributes": {
            "saml.assertion.signature": "false",
            "saml.force.post.binding": "false",
            "saml.multivalued.roles": "false",
            "saml.encrypt": "false",
            "saml.server.signature": "false",
            "saml.server.signature.keyinfo.ext": "false",
            "exclude.session.state.from.auth.response": "false",
            "saml_force_name_id_format": "false",
            "saml.client.signature": "false",
            "tls.client.certificate.bound.access.tokens": "false",
            "saml.authnstatement": "false",
            "display.on.consent.screen": "false",
            "saml.onetimeuse.condition": "false"
          }
        },
        {
          "clientId": "grafana",
          "name": "Grafana",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "redirectUris": [
            "https://grafana.ceres.local/login/generic_oauth"
          ],
          "webOrigins": [
            "https://grafana.ceres.local"
          ],
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true
        },
        {
          "clientId": "mattermost",
          "name": "Mattermost",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "redirectUris": [
            "https://chat.ceres.local/signup/gitlab/complete",
            "https://chat.ceres.local/login/gitlab/complete"
          ],
          "webOrigins": [
            "https://chat.ceres.local"
          ],
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true
        },
        {
          "clientId": "wikijs",
          "name": "Wiki.js",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "redirectUris": [
            "https://wiki.ceres.local/login/callback"
          ],
          "webOrigins": [
            "https://wiki.ceres.local"
          ],
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true
        },
        {
          "clientId": "nextcloud",
          "name": "Nextcloud",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "redirectUris": [
            "https://files.ceres.local/apps/user_oidc/code"
          ],
          "webOrigins": [
            "https://files.ceres.local"
          ],
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true
        },
        {
          "clientId": "oauth2-proxy",
          "name": "OAuth2 Proxy (All services)",
          "enabled": true,
          "protocol": "openid-connect",
          "publicClient": false,
          "redirectUris": [
            "https://mail.ceres.local/oauth2/callback",
            "https://portainer.ceres.local/oauth2/callback",
            "https://db.ceres.local/oauth2/callback",
            "https://minio.ceres.local/oauth2/callback",
            "https://prometheus.ceres.local/oauth2/callback"
          ],
          "webOrigins": [
            "https://*.ceres.local"
          ],
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "admin",
            "description": "Administrator role"
          },
          {
            "name": "user",
            "description": "Standard user role"
          },
          {
            "name": "developer",
            "description": "Developer role"
          }
        ]
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: ceres
spec:
  selector:
    app: keycloak
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data
  namespace: ceres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: ceres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-data
      - name: keycloak-realm
        configMap:
          name: keycloak-realm
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:23.0.0
        args:
        - start-dev
        - --import-realm
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/keycloak/data
        - name: keycloak-realm
          mountPath: /opt/keycloak/data/import/ceres-realm.json
          subPath: ceres-realm.json
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: admin-password
        - name: KC_PROXY
          value: edge
        - name: KC_HOSTNAME_STRICT
          value: 'false'
        - name: KC_HTTP_ENABLED
          value: 'true'
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
