# CERES Mail UI
# Runs as a systemd service on the server host (192.168.1.3:8090)
# and is exposed to the cluster via a Service+Endpoints.
#
# Security: the HTTP server enforces BasicAuth; configure credentials via
# CERES_UI_BASIC_USER / CERES_UI_BASIC_PASS on the host service.
---
apiVersion: v1
kind: Service
metadata:
  name: ceres-mail-ui
  namespace: ceres
spec:
  ports:
    - name: http
      port: 8090
      targetPort: 8090
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ceres-mail-ui
  namespace: ceres
subsets:
  - addresses:
      - ip: 192.168.1.3
    ports:
      - name: http
        port: 8090
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ceres-mail-ui
  namespace: ceres
  annotations:
    cert-manager.io/cluster-issuer: "ceres-ca"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - mail-ui.ceres.local
      secretName: ceres-mail-ui-tls
  rules:
    - host: mail-ui.ceres.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ceres-mail-ui
                port:
                  number: 8090
