#!/usr/bin/env bash
set -euo pipefail

# Creates/updates a single instance-wide config file used by update+deploy and UI services.
# Goal: keep deployments reproducible and avoid manual env exports.

ENV_FILE="${CERES_INSTANCE_ENV_FILE:-/etc/ceres/ceres.env}"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root" >&2
  exit 1
fi

mkdir -p "$(dirname "${ENV_FILE}")"
chmod 700 "$(dirname "${ENV_FILE}")"

# Prefill variables from existing config, if any.
if [ -f "${ENV_FILE}" ]; then
  set -a
  # shellcheck disable=SC1090
  . "${ENV_FILE}"
  set +a
fi

prompt() {
  local var_name="$1"
  local text="$2"
  local default_value="${3:-}"

  local current_value="${!var_name:-}"
  local shown_default="${current_value:-$default_value}"

  if [ -n "${shown_default}" ]; then
    read -r -p "${text} [${shown_default}]: " input
  else
    read -r -p "${text}: " input
  fi

  if [ -z "${input}" ]; then
    input="${shown_default}"
  fi

  printf -v "${var_name}" '%s' "${input}"
}

prompt_secret() {
  local var_name="$1"
  local text="$2"
  local current_value="${!var_name:-}"

  if [ -n "${current_value}" ]; then
    read -r -p "${text} [already set, press Enter to keep]: " input
    if [ -z "${input}" ]; then
      input="${current_value}"
    fi
  else
    read -r -s -p "${text}: " input
    echo ""
  fi

  printf -v "${var_name}" '%s' "${input}"
}

# Defaults
CERES_DOMAIN="${CERES_DOMAIN:-ceres.local}"
CERES_MAIL_MODE="${CERES_MAIL_MODE:-external}"
CERES_MAIL_FROM="${CERES_MAIL_FROM:-no-reply@yourdomain.com}"
CERES_SMTP_HOST="${CERES_SMTP_HOST:-}"
CERES_SMTP_PORT="${CERES_SMTP_PORT:-587}"
CERES_SMTP_USER="${CERES_SMTP_USER:-}"
CERES_SMTP_PASS="${CERES_SMTP_PASS:-}"
CERES_SMTP_STARTTLS="${CERES_SMTP_STARTTLS:-true}"
CERES_SMTP_TLS="${CERES_SMTP_TLS:-false}"

# Proxmox notes updater (optional)
CERES_PROXMOX_NOTES_APPLY="${CERES_PROXMOX_NOTES_APPLY:-false}"
CERES_PROXMOX_NOTES_UPDATE="${CERES_PROXMOX_NOTES_UPDATE:-auto}"

REPO_URL="${REPO_URL:-}"
REPO_DIR="${REPO_DIR:-}"

echo "[CERES] Instance configuration wizard"

echo ""
prompt CERES_DOMAIN "Base domain for services (e.g. company.com)" "ceres.local"

echo ""
prompt CERES_MAIL_MODE "Mail mode (external|internal)" "external"
prompt CERES_MAIL_FROM "From address for system emails" "${CERES_MAIL_FROM}"

echo ""
prompt CERES_SMTP_HOST "SMTP host (e.g. mail.example.com)" "${CERES_SMTP_HOST}"
prompt CERES_SMTP_PORT "SMTP port" "${CERES_SMTP_PORT}"
prompt CERES_SMTP_USER "SMTP username (often full email)" "${CERES_SMTP_USER}"
prompt_secret CERES_SMTP_PASS "SMTP password/app-password"
prompt CERES_SMTP_STARTTLS "SMTP StartTLS (true|false)" "${CERES_SMTP_STARTTLS}"
prompt CERES_SMTP_TLS "SMTP implicit TLS (true|false)" "${CERES_SMTP_TLS}"

echo ""
prompt REPO_URL "(Optional) Git repo URL for update+deploy" "${REPO_URL}"
prompt REPO_DIR "(Optional) Repo directory on server" "${REPO_DIR}"

echo ""
prompt CERES_PROXMOX_NOTES_APPLY "(Optional) Apply Proxmox notes updater (true|false)" "${CERES_PROXMOX_NOTES_APPLY}"
prompt CERES_PROXMOX_NOTES_UPDATE "(Optional) Run Proxmox notes update after deploy (auto|true|false)" "${CERES_PROXMOX_NOTES_UPDATE}"

# Write atomically
TMP_FILE="${ENV_FILE}.tmp"
{
  echo "# CERES instance configuration"
  echo "# Generated by scripts/configure-ceres-instance.sh"
  echo "# Permissions: 600"
  echo ""

  echo "CERES_DOMAIN=${CERES_DOMAIN}"

  echo "CERES_MAIL_MODE=${CERES_MAIL_MODE}"
  echo "CERES_MAIL_FROM=${CERES_MAIL_FROM}"

  if [ -n "${CERES_SMTP_HOST}" ]; then
    echo "CERES_SMTP_HOST=${CERES_SMTP_HOST}"
    echo "CERES_SMTP_PORT=${CERES_SMTP_PORT}"
    [ -n "${CERES_SMTP_USER}" ] && echo "CERES_SMTP_USER=${CERES_SMTP_USER}"
    [ -n "${CERES_SMTP_PASS}" ] && echo "CERES_SMTP_PASS=${CERES_SMTP_PASS}"
    echo "CERES_SMTP_STARTTLS=${CERES_SMTP_STARTTLS}"
    echo "CERES_SMTP_TLS=${CERES_SMTP_TLS}"
  fi

  echo "CERES_PROXMOX_NOTES_APPLY=${CERES_PROXMOX_NOTES_APPLY}"
  echo "CERES_PROXMOX_NOTES_UPDATE=${CERES_PROXMOX_NOTES_UPDATE}"

  [ -n "${REPO_URL}" ] && echo "REPO_URL=${REPO_URL}"
  [ -n "${REPO_DIR}" ] && echo "REPO_DIR=${REPO_DIR}"
} > "${TMP_FILE}"

chmod 600 "${TMP_FILE}"

# Best-effort: avoid leaving secrets in shell history by not echoing values.
# Move into place.
install -m 600 "${TMP_FILE}" "${ENV_FILE}"
rm -f "${TMP_FILE}"

echo "[CERES] Wrote: ${ENV_FILE}"

echo "[CERES] Reloading systemd (best-effort)..."
systemctl daemon-reload || true
systemctl restart ceres-console-ui.service 2>/dev/null || true
systemctl restart ceres-mail-ui.service 2>/dev/null || true

# The update+deploy oneshot is triggered manually; no need to restart it.

echo "[CERES] done"
