#!/usr/bin/env bash
set -euo pipefail

# Minimal wizard for configuring external/hosted SMTP for CERES + Keycloak.
# Writes /etc/ceres/ceres.env (or $CERES_INSTANCE_ENV_FILE) with tight permissions.

ENV_FILE="${CERES_INSTANCE_ENV_FILE:-/etc/ceres/ceres.env}"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root" >&2
  exit 1
fi

mkdir -p "$(dirname "${ENV_FILE}")"
chmod 700 "$(dirname "${ENV_FILE}")"

# Load existing values if present
if [ -f "${ENV_FILE}" ]; then
  set -a
  # shellcheck disable=SC1090
  . "${ENV_FILE}"
  set +a
fi

prompt() {
  local var_name="$1"
  local text="$2"
  local default_value="${3:-}"

  local current_value="${!var_name:-}"
  local shown_default="${current_value:-$default_value}"

  if [ -n "${shown_default}" ]; then
    read -r -p "${text} [${shown_default}]: " input
  else
    read -r -p "${text}: " input
  fi

  if [ -z "${input}" ]; then
    input="${shown_default}"
  fi

  printf -v "${var_name}" '%s' "${input}"
}

prompt_secret() {
  local var_name="$1"
  local text="$2"
  local current_value="${!var_name:-}"

  if [ -n "${current_value}" ]; then
    read -r -p "${text} [already set, press Enter to keep]: " input
    if [ -z "${input}" ]; then
      input="${current_value}"
    fi
  else
    read -r -s -p "${text}: " input
    echo ""
  fi

  printf -v "${var_name}" '%s' "${input}"
}

echo "[CERES] SMTP configuration"

CERES_DOMAIN="${CERES_DOMAIN:-ceres.local}"
CERES_MAIL_MODE="${CERES_MAIL_MODE:-external}"
CERES_MAIL_FROM="${CERES_MAIL_FROM:-no-reply@${CERES_DOMAIN}}"

CERES_SMTP_HOST="${CERES_SMTP_HOST:-}"
CERES_SMTP_PORT="${CERES_SMTP_PORT:-587}"
CERES_SMTP_USER="${CERES_SMTP_USER:-}"
CERES_SMTP_PASS="${CERES_SMTP_PASS:-}"
CERES_SMTP_STARTTLS="${CERES_SMTP_STARTTLS:-true}"
CERES_SMTP_TLS="${CERES_SMTP_TLS:-false}"

prompt CERES_DOMAIN "Base domain" "praximo.tech"
prompt CERES_MAIL_FROM "From address" "no-reply@${CERES_DOMAIN}"
prompt CERES_SMTP_HOST "SMTP host" "mail.${CERES_DOMAIN}"
prompt CERES_SMTP_PORT "SMTP port" "${CERES_SMTP_PORT}"
prompt CERES_SMTP_USER "SMTP username" "no-reply@${CERES_DOMAIN}"
prompt_secret CERES_SMTP_PASS "SMTP password/app-password"
prompt CERES_SMTP_STARTTLS "SMTP StartTLS (true|false)" "${CERES_SMTP_STARTTLS}"
prompt CERES_SMTP_TLS "SMTP implicit TLS (true|false, for 465)" "${CERES_SMTP_TLS}"

CERES_MAIL_MODE="external"

TMP_FILE="${ENV_FILE}.tmp"
{
  echo "# CERES instance configuration"
  echo "# Generated by scripts/configure-ceres-smtp.sh"
  echo "# Permissions: 600"
  echo ""
  echo "CERES_DOMAIN=${CERES_DOMAIN}"
  echo "CERES_MAIL_MODE=${CERES_MAIL_MODE}"
  echo "CERES_MAIL_FROM=${CERES_MAIL_FROM}"
  echo "CERES_SMTP_HOST=${CERES_SMTP_HOST}"
  echo "CERES_SMTP_PORT=${CERES_SMTP_PORT}"
  echo "CERES_SMTP_USER=${CERES_SMTP_USER}"
  echo "CERES_SMTP_PASS=${CERES_SMTP_PASS}"
  echo "CERES_SMTP_STARTTLS=${CERES_SMTP_STARTTLS}"
  echo "CERES_SMTP_TLS=${CERES_SMTP_TLS}"

  # Preserve Proxmox notes settings if present
  [ -n "${CERES_PROXMOX_NOTES_APPLY:-}" ] && echo "CERES_PROXMOX_NOTES_APPLY=${CERES_PROXMOX_NOTES_APPLY}"
  [ -n "${CERES_PROXMOX_NOTES_UPDATE:-}" ] && echo "CERES_PROXMOX_NOTES_UPDATE=${CERES_PROXMOX_NOTES_UPDATE}"

  # Preserve repo settings if present
  [ -n "${REPO_URL:-}" ] && echo "REPO_URL=${REPO_URL}"
  [ -n "${REPO_DIR:-}" ] && echo "REPO_DIR=${REPO_DIR}"
} > "${TMP_FILE}"

chmod 600 "${TMP_FILE}"
install -m 600 "${TMP_FILE}" "${ENV_FILE}"
rm -f "${TMP_FILE}"

echo "[CERES] Wrote: ${ENV_FILE}"

# Best-effort checks (helpful on hosted mail setups)
check_tcp() {
  local host="$1"
  local port="$2"

  if command -v timeout >/dev/null 2>&1; then
    timeout 5 bash -c "cat < /dev/null > /dev/tcp/${host}/${port}" >/dev/null 2>&1
    return $?
  fi

  # no timeout available; try quick connect anyway
  (cat < /dev/null > /dev/tcp/${host}/${port}) >/dev/null 2>&1
}

echo "[CERES] Checking SMTP connectivity to ${CERES_SMTP_HOST}:${CERES_SMTP_PORT} (best-effort)..."
if check_tcp "${CERES_SMTP_HOST}" "${CERES_SMTP_PORT}"; then
  echo "[CERES] SMTP TCP connect OK"
else
  echo "[CERES] WARNING: cannot connect to ${CERES_SMTP_HOST}:${CERES_SMTP_PORT} from this server" >&2
fi

if command -v openssl >/dev/null 2>&1; then
  echo "[CERES] Checking TLS certificate SAN for ${CERES_SMTP_HOST} (best-effort)..."
  if [ "${CERES_SMTP_TLS}" = "true" ]; then
    tls_out=$(echo | timeout 10 openssl s_client -connect "${CERES_SMTP_HOST}:${CERES_SMTP_PORT}" -servername "${CERES_SMTP_HOST}" 2>/dev/null \
      | openssl x509 -noout -ext subjectAltName 2>/dev/null || true)
  elif [ "${CERES_SMTP_STARTTLS}" = "true" ]; then
    tls_out=$(echo | timeout 10 openssl s_client -starttls smtp -connect "${CERES_SMTP_HOST}:${CERES_SMTP_PORT}" -servername "${CERES_SMTP_HOST}" 2>/dev/null \
      | openssl x509 -noout -ext subjectAltName 2>/dev/null || true)
  else
    tls_out=""
  fi

  if [ -n "${tls_out}" ] && echo "${tls_out}" | grep -qi "DNS:${CERES_SMTP_HOST}"; then
    echo "[CERES] TLS SAN includes ${CERES_SMTP_HOST}"
  elif [ -n "${tls_out}" ]; then
    echo "[CERES] WARNING: TLS SAN may not include ${CERES_SMTP_HOST}; clients may fail TLS verification" >&2
    echo "${tls_out}" | sed -n '1,3p' >&2 || true
  fi
fi

# Export variables so subprocesses (Keycloak config, ceres mail test) can read them.
export CERES_DOMAIN CERES_MAIL_MODE CERES_MAIL_FROM
export CERES_SMTP_HOST CERES_SMTP_PORT CERES_SMTP_USER CERES_SMTP_PASS CERES_SMTP_STARTTLS CERES_SMTP_TLS

# Configure Keycloak SMTP best-effort if we're inside the repo checkout
if [ -f "./scripts/configure-keycloak-smtp.sh" ]; then
  bash ./scripts/configure-keycloak-smtp.sh || echo "[CERES] Keycloak SMTP config skipped/failed (non-fatal)" >&2
fi

# Optional: send a test email
TEST_TO="${CERES_SMTP_TEST_TO:-}"
if [ -z "${TEST_TO}" ]; then
  read -r -p "Test email recipient (optional, press Enter to skip): " TEST_TO
fi

if [ -n "${TEST_TO}" ] && [ -x "./bin/ceres" ]; then
  echo "[CERES] Sending test email to ${TEST_TO}..."
  ./bin/ceres mail test "${TEST_TO}" || echo "[CERES] Test email failed" >&2
elif [ -n "${TEST_TO}" ]; then
  echo "[CERES] Skipping test email: ./bin/ceres not found/executable (run from repo root)" >&2
fi

echo "[CERES] done"
