# ============================================================================
# CERES Flux CD - Complete GitOps Configuration
# ============================================================================

---
# Git Repository Source
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ceres
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/skulesh01/Ceres
  ref:
    branch: main
  secretRef:
    name: git-credentials

---
# Helm Repository - Bitnami (PostgreSQL, Redis)
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami

---
# Helm Repository - Prometheus Community
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts

---
# Helm Repository - Grafana
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts

---
# Helm Repository - Jetstack (Cert-Manager)
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 5m
  url: https://charts.jetstack.io

---
# Helm Repository - Ingress-Nginx
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m
  url: https://kubernetes.github.io/ingress-nginx

---
# ============================================================================
# CERES Namespace
# ============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: ceres

---
# ============================================================================
# CERES Core Infrastructure Release
# ============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceres-infrastructure
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ceres
      sourceRef:
        kind: GitRepository
        name: ceres
      interval: 5m
  values:
    global:
      domain: ceres.local
      environment: production
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true

---
# ============================================================================
# PostgreSQL Helm Release
# ============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: ceres
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "12.1.x"
  values:
    auth:
      username: ceres
      password: changeme
      database: ceres
    primary:
      persistence:
        enabled: true
        size: 100Gi
        storageClassName: ceres-database
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

---
# ============================================================================
# Redis Helm Release
# ============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: ceres
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "17.x.x"
  values:
    auth:
      enabled: true
      password: changeme
    master:
      persistence:
        enabled: true
        size: 10Gi
        storageClassName: ceres-data

---
# ============================================================================
# Cert-Manager for TLS
# ============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: "v1.13.x"
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    global:
      leaderElection:
        namespace: cert-manager

---
# ============================================================================
# Ingress-Nginx Controller
# ============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: "4.x.x"
  values:
    controller:
      service:
        type: LoadBalancer
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

---
# ============================================================================
# Prometheus Stack
# ============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: "54.x.x"
  values:
    prometheus:
      prometheusSpec:
        retention: 30d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: ceres-data
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
    grafana:
      adminPassword: changeme
      persistence:
        enabled: true
        storageClassName: ceres-data
        size: 10Gi

---
# ============================================================================
# Loki (Logging) Stack
# ============================================================================

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: "2.x.x"
  values:
    loki:
      persistence:
        enabled: true
        storageClassName: ceres-data
        size: 30Gi
    promtail:
      enabled: true

---
# ============================================================================
# Service Monitor for CERES Services
# ============================================================================

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ceres-services
  namespace: ceres
spec:
  selector:
    matchLabels:
      monitoring: enabled
  endpoints:
  - port: metrics
    interval: 30s
