apiVersion: v1
kind: Namespace
metadata:
  name: ceres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceres-config
  namespace: ceres
data:
  DOMAIN_NAME: "{{ .Values.global.domain }}"
  ENVIRONMENT: "{{ .Values.global.environment }}"
  LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: ceres-secrets
  namespace: ceres
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password }}"
  REDIS_PASSWORD: "{{ .Values.redis.auth.password }}"
  KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.keycloak.auth.adminPassword }}"
  GITLAB_ROOT_PASSWORD: "{{ .Values.gitlab.initialRootPassword }}"
  NEXTCLOUD_ADMIN_PASSWORD: "{{ .Values.nextcloud.admin.password }}"
  MATTERMOST_POSTGRES_PASSWORD: "{{ .Values.mattermost.postgresql.password }}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceres-database
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  encrypted: "true"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceres-data
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  iops: "1000"
  throughput: "250"
allowVolumeExpansion: true
