---
# Ansible Inventory - Generated by Terraform
# DO NOT EDIT MANUALLY - Changes will be overwritten

all:
  vars:
    ansible_user: ${ssh_user}
    ansible_ssh_private_key_file: ${ssh_key}
    ansible_python_interpreter: /usr/bin/python3
    domain: ${domain}

ceres_servers:
  children:
    core:
      hosts:
        ${core_vm.name}:
          ansible_host: ${core_vm.default_ipv4_address}
          role: core
          services:
            - postgresql
            - redis
            - keycloak
    
    apps:
      hosts:
        ${apps_vm.name}:
          ansible_host: ${apps_vm.default_ipv4_address}
          role: apps
          services:
            - gitlab
            - zulip
            - nextcloud
            - mayan
    
    edge:
      hosts:
        ${edge_vm.name}:
          ansible_host: ${edge_vm.default_ipv4_address}
          role: edge
          services:
            - caddy
            - prometheus
            - grafana
            - portainer
            - wireguard
